### ISSUE TITLE
Kind request to you, sar

### ISSUE THREAD

**Issue by neelkamath** [AshtrayShetty/Bootleg-POKeGAME#1]
Highly Respected Sar,

Myself Kamath from Chevar in Kerala.

I may please requesting you to add the downloadable files, sar. I very much appreciate enjoying your highly esteemed bootyleg-pokergame.

I hoping I not troubled your valuable time, saar. But I could not able to find compiler instructions to do myself.

Thanking you,
Neel Kamath Chevar House

**Comment by AshtrayShetty** [comment]
Respected saar,
             I very much is respecting that input you is gaven. This is just a work in progress. I will is make sure that that README that one is added in the close future.

Humble Regods,
Ashtroy Sethia
