### ISSUE TITLE
Save game

### ISSUE THREAD

**Issue by AshtrayShetty** [AshtrayShetty/Bootleg-POKeGAME#13]
Currently, as a sample, the game data is stored in a text file. This file is easy to manipulate and leads to unfair gameplay. A new implementation (and a new format probably) of the saved file would be much required.

**Comment by jhueppauff** [comment]
I'd like to work on this. But I wonder how a "manipulation free" savefile would look like.
As everything in on the client, even if we would store it binary, it could be modified.

My idea would be to encrypt it, but everyone who reads the source code would know how to decrypt ;-)

**Comment by AshtrayShetty** [comment]
Your suggestion sounds good!! 
I dunno if the general public would be getting the main application though. This project was mostly a tribute project and I want it to function properly, in all aspects. 
If you're able to come up with a good enough encryption algorithm, you're more than welcome to work on this issue!

**Comment by jhueppauff** [comment]
Created PR ;-)
