### ISSUE TITLE
Progress bar color change indicating HP range

### ISSUE THREAD

**Issue by AshtrayShetty** [AshtrayShetty/Bootleg-POKeGAME#14]
The progress bar has been beautifully animated, what's required now is to display different colors based on what range the HP of a pokemon is at. 

Ex:
60-100% - Green
30-59% - Yellow
0-30% - Red

This is just so that the player might not get misguided by the remaining width of the progress bar. Color scheme may be changed to make it look more attractive

**Comment by Reisclef** [comment]
Do you want a fade between each colour, or a hard change between the above examples? i.e. #FF0000, #FFFF00, #0000FF, or some variation, based on its value?

**Comment by AshtrayShetty** [comment]
Probably a fade. But if some other transition mode seems to benefit the UI, then that

**Comment by preeti13456** [comment]
Interested.

**Comment by AshtrayShetty** [comment]
Hey @preeti13456 !
So @Reisclef commented on the issue first. If he's okay with letting you work on the issue, then I have no objections.

**Comment by Reisclef** [comment]
Hey @AshtrayShetty , @preeti13456 , I'd really like to work on this, but I might not be able to make the time for a bit, so I'm happy for @preeti13456 to work on it. :)

**Comment by AshtrayShetty** [comment]
Hey! Sorry to say but this issue has been resolved by @giribroba . Will close it now.
