### ISSUE TITLE
Feature Request - Loading Screen 

### ISSUE THREAD

**Issue by thazhemadam** [AshtrayShetty/Bootleg-POKeGAME#2]
Please create a loading screen for the game with the following important information.
![image](https://user-images.githubusercontent.com/47104651/86033020-eaa6ae00-ba55-11ea-8ee6-aa80ec25dce2.png)

**Comment by AshtrayShetty** [comment]
Of course Of course. Thanks for the image. Will make sure I put it in the readme as well. Do you happen to have more of such images? 😆

**Comment by thazhemadam** [comment]
Not presently, but will share immediately if I do come across some.
