### ISSUE TITLE
Improve matchmaking

### ISSUE THREAD

**Issue by AshtrayShetty** [AshtrayShetty/Bootleg-POKeGAME#7]
Currently, when battling wild pokemon, the level of the wild pokemon is randomly selected. This leads to situation where your pokemon at level 1 might be put in battle against a level 54 wild pokemon. Though this may simulate the nature of the wild battles very well, it hinders player progression. It would be nice to pit players in battle against pokemon with level of around a similar level as theirs. 
Not necessarily the same level as the player pokemon though, **SIMILAR**. For example, if the player has pokemon in their inventory in the range of levels 1-32, they might be put into battles with wild pokemon in the range of levels 5-43 (something like that).

**Comment by summerag** [comment]
This project seems pretty cool. Can I take a crack at this issue?

**Comment by AshtrayShetty** [comment]
yeah sure!!!

**Comment by AshtrayShetty** [comment]
#9 was merged
